apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      volumes:
        - name: project-image
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: todo
          image: todo
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: project-image
            mountPath: /usr/src/app/files
