apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomlog-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomlog
  template:
    metadata:
      labels:
        app: randomlog
    spec:
      containers:
        - name: randomlog
          image: randomlog
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
