apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomlog-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: randomlog
  template:
    metadata:
      labels:
        app: randomlog
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: logwriter
          image: stringgenerator
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-log
            mountPath: /usr/src/app/files
        - name: logreader
          image: stringreader
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          volumeMounts:
          - name: shared-log
            mountPath: /usr/src/app/files
        
